create table categoria_inativacao_produto (
  codigo varchar(40) primary key,
  descricao varchar(500) not null
);
insert into categoria_inativacao_produto(codigo, descricao) values
  ('FORA_DE_MERCADO', 'Produto fora de mercado ou fora da linha comercial'),
  ('DESCONTINUADO', 'Produto descontinuado sem previsão de reposição'),
  ('ERRO_CADASTRO', 'Cadastro com erro que exige correção antes da venda');
create table categoria_ativacao_produto (
  codigo varchar(40) primary key,
  descricao varchar(500) not null
);
insert into categoria_ativacao_produto(codigo, descricao) values
  ('RETORNO_AO_MERCADO', 'Produto retorna ao mercado após período indisponível'),
  ('REPOSICAO_ESTOQUE', 'Produto reativado com reposição de estoque'),
  ('CORRECAO_CADASTRO', 'Produto reativado após correção cadastral');
create table produto (
  id bigint generated by default as identity primary key,
  codigo varchar(20),
  nome varchar(150) not null,
  marca varchar(80) not null,
  preco numeric(12,2) not null check (preco >= 0),
  estoque integer not null check (estoque >= 0),
  ativo boolean not null default true,
  visivel boolean not null default true,
  categoria_inativacao varchar(40) references categoria_inativacao_produto(codigo),
  justificativa_inativacao text,
  inativado_em timestamp with time zone,
  categoria_ativacao varchar(40) references categoria_ativacao_produto(codigo),
  justificativa_ativacao text,
  ativado_em timestamp with time zone,
  criado_em timestamp with time zone not null,
  atualizado_em timestamp with time zone not null
);
update produto set codigo = 'PRD-' || lpad(id::text, greatest(6,length(id::text)), '0') where codigo is null;
alter table produto alter column codigo set not null;
create function atribuir_codigo_produto() returns trigger language plpgsql as $$
begin
 if TG_OP = 'INSERT' then NEW.codigo := 'PRD-' || lpad(NEW.id::text, greatest(6,length(NEW.id::text)), '0');
 elsif NEW.codigo is distinct from OLD.codigo then raise exception 'Código do produto é imutável'; end if;
 return NEW;
end $$;
create trigger codigo_produto before insert or update of codigo on produto for each row execute function atribuir_codigo_produto();
create table auditoria_produto (
  id bigint generated by default as identity primary key,
  produto_id bigint not null references produto(id),
  ocorrida_em timestamp with time zone not null,
  ator varchar(80) not null,
  operacao varchar(50) not null,
  alteracoes text not null,
  entidade varchar(80) not null default 'PRODUTO',
  entidade_id bigint,
  dados_anteriores jsonb,
  dados_novos jsonb
);
create index auditoria_produto_data on auditoria_produto(produto_id, ocorrida_em desc);
