spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://127.0.0.1:5433/aura_lab}
    username: ${DB_USER:aura}
    password: ${DB_PASSWORD:aura}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
server:
  port: ${PORT:4200}
