import { criarNavegacaoAdmin } from "./adminLayout.js";
import { escaparHtml as e } from "./utilitarios.js";
export const status = (v) =>
  `<span class="status ${v ? "ok" : ""}">${v ? "ATIVO" : "INATIVO"}</span>`;
export const layout = (conteudo) =>
  `<main class="admin clientes-admin"><div>${criarNavegacaoAdmin("Clientes", "data-api-link")}<section class="admin-main"><div class="admin-topbar"><div><span class="eyebrow">Administração</span><h1>Clientes</h1></div><span class="status ok">ADMIN_DEMO</span></div><div data-testid="clientes-conteudo">${conteudo}</div></section></div></main>`;
export const valor = (d, k) => e(d?.[k] ?? "");
export const camposPessoais = (d = {}, senha = false) =>
  `<div class="row g-3"><div class="col-md-6"><label>Nome completo<input data-testid="nome" class="form-control" name="nome" value="${valor(d, "nome")}" required></label></div><div class="col-md-3"><label>CPF<input data-testid="cpf" class="form-control" name="cpf" value="${valor(d, "cpf")}" required></label></div><div class="col-md-3"><label>Gênero<input class="form-control" name="genero" value="${valor(d, "genero")}" required></label></div><div class="col-md-6"><label>E-mail<input data-testid="email" class="form-control" type="email" name="email" value="${valor(d, "email")}" required></label></div><div class="col-md-3"><label>Nascimento<input class="form-control" type="date" name="nascimento" value="${valor(d, "nascimento")}" required></label></div><div class="col-md-3"><label>Tipo de telefone<select class="form-select" name="telefoneTipo"><option ${d.telefoneTipo === "Celular" ? "selected" : ""}>Celular</option><option ${d.telefoneTipo === "Residencial" ? "selected" : ""}>Residencial</option><option ${d.telefoneTipo === "Comercial" ? "selected" : ""}>Comercial</option></select></label></div><div class="col-md-2"><label>DDD<input class="form-control" name="telefoneDdd" value="${valor(d, "telefoneDdd")}" required></label></div><div class="col-md-4"><label>Telefone<input class="form-control" name="telefoneNumero" value="${valor(d, "telefoneNumero")}" required></label></div>${senha ? `<div class="col-md-3"><label>Senha<input data-testid="senha" class="form-control" type="password" name="senha" required></label></div><div class="col-md-3"><label>Confirmar senha<input data-testid="confirmacao-senha" class="form-control" type="password" name="confirmacaoSenha" required></label></div>` : ""}</div>`;
export const camposEndereco = (d = {}, prefix = "") =>
  `<div class="row g-3"><div class="col-md-4"><label>Apelido<input class="form-control" name="${prefix}apelido" value="${valor(d, "apelido")}" required></label></div><div class="col-md-4"><label>Tipo de residência<input class="form-control" name="${prefix}tipoResidencia" value="${valor(d, "tipoResidencia")}" required></label></div><div class="col-md-4"><label>Tipo de logradouro<input class="form-control" name="${prefix}tipoLogradouro" value="${valor(d, "tipoLogradouro")}" required></label></div><div class="col-md-6"><label>Logradouro<input class="form-control" name="${prefix}logradouro" value="${valor(d, "logradouro")}" required></label></div><div class="col-md-2"><label>Número<input class="form-control" name="${prefix}numero" value="${valor(d, "numero")}" required></label></div><div class="col-md-4"><label>Bairro<input class="form-control" name="${prefix}bairro" value="${valor(d, "bairro")}" required></label></div><div class="col-md-3"><label>CEP<input class="form-control" name="${prefix}cep" value="${valor(d, "cep")}" required></label></div><div class="col-md-3"><label>Cidade<input class="form-control" name="${prefix}cidade" value="${valor(d, "cidade")}" required></label></div><div class="col-md-2"><label>Estado<input class="form-control" name="${prefix}estado" value="${valor(d, "estado")}" required></label></div><div class="col-md-4"><label>País<input class="form-control" name="${prefix}pais" value="${valor(d, "pais") || "Brasil"}" required></label></div><div class="col-12"><label>Complemento<input class="form-control" name="${prefix}complemento" maxlength="100" value="${valor(d, "complemento")}"></label></div><div class="col-12"><label>Observações<input class="form-control" name="${prefix}observacoes" value="${valor(d, "observacoes")}"></label></div></div>`;
