/**
 * Massa de dados demonstrativa do protótipo.
 * Estes objetos simulam a futura resposta da API e nunca devem conter dados reais de cartão.
 */

export const VERSAO_SCHEMA = 3;

// Produtos iniciais exibidos no catálogo e usados nos pedidos demonstrativos.
const PRODUTOS_INICIAIS = [
  {
    id: 1,
    code: "AUR-001",
    name: "Base Sérum Radiance 24h",
    brand: "AURA LAB",
    categories: ["Face", "Maquiagem"],
    price: 129.9,
    cost: 52,
    tone: "Média 3",
    finish: "Natural",
    skin: "Mista",
    volume: "30 ml",
    ingredients: "Niacinamida, esqualano, vitamina E",
    stock: 14,
    visible: true,
    description:
      "Cobertura construível e brilho saudável para uma pele naturalmente iluminada.",
    art: "#c97668",
    image: "",
  },
  {
    id: 2,
    code: "AUR-002",
    name: "Balm de Limpeza Cloud Melt",
    brand: "NÉVOA",
    categories: ["Skincare", "Limpeza Facial"],
    price: 82.9,
    cost: 29,
    tone: "—",
    finish: "Conforto",
    skin: "Todos os tipos",
    volume: "100 g",
    ingredients: "Ceramidas, camélia, pantenol",
    stock: 7,
    visible: true,
    description: "Remove maquiagem e protetor solar sem repuxar a pele.",
    art: "#a887ab",
    image: "",
  },
  {
    id: 3,
    code: "AUR-003",
    name: "Blush Líquido Flush Bloom",
    brand: "AURA LAB",
    categories: ["Face", "Maquiagem"],
    price: 74.9,
    cost: 25,
    tone: "Rosa pétala",
    finish: "Viçoso",
    skin: "Todos os tipos",
    volume: "8 ml",
    ingredients: "Óleo de rosa, vitamina E",
    stock: 23,
    visible: true,
    description: "Cor leve, modulável e luminosa que se funde à pele.",
    art: "#c85579",
    image: "",
  },
  {
    id: 4,
    code: "AUR-004",
    name: "Paleta Olhar em Camadas",
    brand: "ORIGEM",
    categories: ["Olhos", "Maquiagem"],
    price: 159.9,
    cost: 68,
    tone: "Terrosos",
    finish: "Acetinado",
    skin: "Todos os tipos",
    volume: "9 cores",
    ingredients: "Mica, óleo de uva",
    stock: 5,
    visible: true,
    description:
      "Nove sombras em neutros contemporâneos para construir o olhar.",
    art: "#8b6657",
    image: "",
  },
  {
    id: 5,
    code: "AUR-005",
    name: "Óleo Labial Golden Hour",
    brand: "SOLAR",
    categories: ["Lábios", "Maquiagem"],
    price: 69.9,
    cost: 22,
    tone: "Âmbar",
    finish: "Brilhante",
    skin: "Todos os tipos",
    volume: "6 ml",
    ingredients: "Jojoba, vitamina E, karité",
    stock: 17,
    visible: true,
    description:
      "Brilho dourado translúcido e nutrição confortável para os lábios.",
    art: "#d1974d",
    image: "",
  },
  {
    id: 6,
    code: "AUR-006",
    name: "Bruma Reset & Glow",
    brand: "NÉVOA",
    categories: ["Skincare", "Hidratantes", "Bruma"],
    price: 89.9,
    cost: 31,
    tone: "—",
    finish: "Hidratante",
    skin: "Sensível",
    volume: "120 ml",
    ingredients: "Água termal, aloe vera, betaína",
    stock: 9,
    visible: true,
    description: "Refresca, hidrata e devolve viço em qualquer momento do dia.",
    art: "#6c9ca6",
    image: "",
  },
  {
    id: 7,
    code: "AUR-007",
    name: "Máscara Lash Atelier",
    brand: "AURA LAB",
    categories: ["Olhos", "Maquiagem"],
    price: 96.9,
    cost: 36,
    tone: "Preto",
    finish: "Volume",
    skin: "Todos os tipos",
    volume: "10 g",
    ingredients: "Pantenol, cera de carnaúba",
    stock: 11,
    visible: true,
    description:
      "Pincel preciso, volume leve e definição que respeita os cílios.",
    art: "#593b45",
    image: "",
  },
  {
    id: 8,
    code: "AUR-008",
    name: "Batom Soft Blur",
    brand: "SOLAR",
    categories: ["Lábios", "Maquiagem"],
    price: 78.9,
    cost: 26,
    tone: "Terracota",
    finish: "Semi-matte",
    skin: "Todos os tipos",
    volume: "3,5 g",
    ingredients: "Ácido hialurônico, vitamina E",
    stock: 19,
    visible: true,
    description: "Pigmento uniforme, acabamento aveludado e toque confortável.",
    art: "#ab554b",
    image: "",
  },
];

// Endereços compartilhados entre cliente e pedidos para deixar o mock menor e consistente.
const ENDERECO_RESIDENCIAL = {
  id: "addr-1",
  label: "Minha casa",
  purposes: ["COBRANCA", "ENTREGA"],
  residenceType: "Apartamento",
  streetType: "Avenida",
  street: "Paulista",
  number: "1578",
  district: "Bela Vista",
  cep: "01310-100",
  city: "São Paulo",
  state: "SP",
  country: "Brasil",
  observations: "Apto 82",
  preferred: true,
  active: true,
};

const ENDERECO_TRABALHO = {
  id: "addr-2",
  label: "Trabalho",
  purposes: ["ENTREGA"],
  residenceType: "Comercial",
  streetType: "Rua",
  street: "Funchal",
  number: "418",
  district: "Vila Olímpia",
  cep: "04538-132",
  city: "São Paulo",
  state: "SP",
  country: "Brasil",
  observations: "8º andar",
  preferred: false,
  active: true,
};

export const DADOS_INICIAIS = {
  // A versão ajuda o store a descartar dados antigos salvos no localStorage.
  version: VERSAO_SCHEMA,
  products: PRODUTOS_INICIAIS,

  // Clientes simulados cobrem cenários de cadastro ativo, cartão salvo e conta inativa.
  customers: [
    {
      id: "cli-1",
      name: "Marina Costa",
      cpf: "123.456.789-00",
      birthDate: "1993-04-18",
      gender: "Feminino",
      email: "marina@exemplo.com",
      phoneType: "Celular",
      phoneDdd: "11",
      phoneNumber: "99999-0000",
      phone: "Celular (11) 99999-0000",
      passwordChangedAt: "2026-08-01T12:00:00.000Z",
      active: true,
      addresses: [ENDERECO_RESIDENCIAL, ENDERECO_TRABALHO],
      cards: [
        {
          id: "card-1",
          brand: "Visa",
          label: "Visa",
          holder: "MARINA COSTA",
          last4: "4821",
          preferred: true,
          active: true,
        },
        {
          id: "card-2",
          brand: "Mastercard",
          label: "Mastercard",
          holder: "MARINA COSTA",
          last4: "0908",
          preferred: false,
          active: true,
        },
      ],
    },
    {
      id: "cli-2",
      name: "Ana Souza",
      cpf: "987.654.321-00",
      birthDate: "1988-11-02",
      gender: "Feminino",
      email: "ana@exemplo.com",
      phoneType: "Celular",
      phoneDdd: "21",
      phoneNumber: "98888-1212",
      phone: "Celular (21) 98888-1212",
      passwordChangedAt: "2026-08-01T12:00:00.000Z",
      active: true,
      addresses: [
        {
          ...ENDERECO_RESIDENCIAL,
          id: "addr-3",
          label: "Casa",
          city: "Rio de Janeiro",
          state: "RJ",
          streetType: "Rua",
          street: "do Catete",
          number: "120",
        },
      ],
      cards: [
        {
          id: "card-3",
          brand: "Elo",
          label: "Elo",
          holder: "ANA SOUZA",
          last4: "7712",
          preferred: true,
          active: true,
        },
      ],
    },
    {
      id: "cli-3",
      name: "Bianca Lima",
      cpf: "555.444.333-22",
      birthDate: "1996-02-12",
      gender: "Feminino",
      email: "bianca@exemplo.com",
      phoneType: "Celular",
      phoneDdd: "31",
      phoneNumber: "97777-3434",
      phone: "Celular (31) 97777-3434",
      passwordChangedAt: "2026-08-01T12:00:00.000Z",
      active: false,
      addresses: [
        {
          ...ENDERECO_RESIDENCIAL,
          id: "addr-4",
          label: "Residencial",
          city: "Belo Horizonte",
          state: "MG",
          streetType: "Avenida",
          street: "Afonso Pena",
          number: "900",
        },
      ],
      cards: [],
    },
  ],
  // Cliente pré-selecionado para que perfil e pedidos possam ser demonstrados ao abrir o protótipo.
  currentCustomerId: "cli-1",
  cart: {},
  reservation: null,
  expiredItems: [],
  checkout: {
    // Guarda escolhas temporárias entre as etapas de endereço, pagamento e confirmação.
    addressId: "addr-1",
    newAddress: null,
    promoCouponId: null,
    exchangeCouponIds: [],
    cardAllocations: {},
    lastOrderId: null,
  },

  // Cupons promocionais são globais; cupons de troca pertencem a um cliente.
  coupons: [
    {
      id: "promo-1",
      customerId: null,
      code: "AURA10",
      type: "PROMOCIONAL",
      mode: "PERCENTUAL",
      value: 10,
      balance: null,
      validUntil: "2026-12-31",
      minPurchase: 0,
      limit: 100,
      uses: 2,
      active: true,
    },
    {
      id: "promo-2",
      customerId: null,
      code: "BEMVINDA20",
      type: "PROMOCIONAL",
      mode: "FIXO",
      value: 20,
      balance: null,
      validUntil: "2026-10-31",
      minPurchase: 99,
      limit: 50,
      uses: 8,
      active: true,
    },
    {
      id: "trade-1",
      customerId: "cli-1",
      code: "TROCA-50",
      type: "TROCA",
      mode: "CREDITO",
      value: 50,
      balance: 50,
      validUntil: "2027-02-28",
      active: true,
      sourceExchangeId: "troca-5",
    },
    {
      id: "trade-2",
      customerId: "cli-1",
      code: "TROCA-80",
      type: "TROCA",
      mode: "CREDITO",
      value: 80,
      balance: 32.5,
      validUntil: "2027-01-31",
      active: true,
      sourceExchangeId: "troca-7",
    },
  ],

  // Pedidos começam em estados diferentes para demonstrar todas as ações administrativas.
  orders: [
    {
      id: "#AUR-25001",
      customerId: "cli-1",
      date: "12/08/2026",
      items: [{ productId: 1, quantity: 1, unitPrice: 129.9 }],
      subtotal: 129.9,
      shipping: 14.9,
      discount: 0,
      total: 144.8,
      status: "EM_ABERTO",
      address: ENDERECO_RESIDENCIAL,
      payments: [{ type: "CARTAO", label: "Visa final 4821", amount: 144.8 }],
      history: [
        {
          status: "EM_ABERTO",
          at: "2026-08-12T10:00:00.000Z",
          actor: "CLIENTE",
        },
      ],
    },
    {
      id: "#AUR-25002",
      customerId: "cli-2",
      date: "13/08/2026",
      items: [{ productId: 5, quantity: 1, unitPrice: 69.9 }],
      subtotal: 69.9,
      shipping: 24.9,
      discount: 0,
      total: 94.8,
      status: "EM_PROCESSAMENTO",
      address: { ...ENDERECO_RESIDENCIAL, city: "Rio de Janeiro", state: "RJ" },
      payments: [{ type: "CARTAO", label: "Elo final 7712", amount: 94.8 }],
      history: [
        {
          status: "EM_ABERTO",
          at: "2026-08-13T10:00:00.000Z",
          actor: "CLIENTE",
        },
        {
          status: "EM_PROCESSAMENTO",
          at: "2026-08-13T10:05:00.000Z",
          actor: "ADMIN",
        },
      ],
    },
    {
      id: "#AUR-25003",
      customerId: "cli-1",
      date: "14/08/2026",
      items: [{ productId: 2, quantity: 1, unitPrice: 82.9 }],
      subtotal: 82.9,
      shipping: 14.9,
      discount: 0,
      total: 97.8,
      status: "PAGAMENTO_REALIZADO",
      address: ENDERECO_TRABALHO,
      payments: [
        { type: "CARTAO", label: "Mastercard final 0908", amount: 97.8 },
      ],
      stockCommitted: true,
      history: [
        {
          status: "EM_ABERTO",
          at: "2026-08-14T09:00:00.000Z",
          actor: "CLIENTE",
        },
        {
          status: "EM_PROCESSAMENTO",
          at: "2026-08-14T09:10:00.000Z",
          actor: "ADMIN",
        },
        {
          status: "PAGAMENTO_REALIZADO",
          at: "2026-08-14T09:12:00.000Z",
          actor: "ADMIN",
        },
      ],
    },
    {
      id: "#AUR-25004",
      customerId: "cli-1",
      date: "15/08/2026",
      items: [{ productId: 7, quantity: 1, unitPrice: 96.9 }],
      subtotal: 96.9,
      shipping: 14.9,
      discount: 0,
      total: 111.8,
      status: "EM_TRANSITO",
      address: ENDERECO_RESIDENCIAL,
      payments: [{ type: "CARTAO", label: "Visa final 4821", amount: 111.8 }],
      stockCommitted: true,
      history: [
        {
          status: "PAGAMENTO_REALIZADO",
          at: "2026-08-15T09:00:00.000Z",
          actor: "ADMIN",
        },
        {
          status: "EM_TRANSITO",
          at: "2026-08-15T14:00:00.000Z",
          actor: "ADMIN",
        },
      ],
    },
    {
      id: "#AUR-25005",
      customerId: "cli-1",
      date: "05/08/2026",
      deliveredAt: "2026-08-10",
      items: [
        { productId: 3, quantity: 2, unitPrice: 74.9 },
        { productId: 8, quantity: 1, unitPrice: 78.9 },
      ],
      subtotal: 228.7,
      shipping: 0,
      discount: 22.87,
      total: 205.83,
      status: "ENTREGUE",
      address: ENDERECO_RESIDENCIAL,
      payments: [
        { type: "CUPOM_PROMOCIONAL", label: "AURA10", amount: 22.87 },
        { type: "CUPOM_TROCA", label: "TROCA-50", amount: 50 },
        { type: "CARTAO", label: "Visa final 4821", amount: 100 },
        { type: "CARTAO", label: "Mastercard final 0908", amount: 55.83 },
      ],
      stockCommitted: true,
      history: [
        {
          status: "EM_TRANSITO",
          at: "2026-08-09T10:00:00.000Z",
          actor: "ADMIN",
        },
        {
          status: "ENTREGUE",
          at: "2026-08-10T11:00:00.000Z",
          actor: "CLIENTE",
        },
      ],
    },
  ],

  // Trocas simulam cada etapa do ciclo: solicitada, aceita, enviada, recebida e processada.
  exchanges: [
    {
      id: "troca-1",
      orderId: "#AUR-25005",
      customerId: "cli-1",
      productId: 3,
      quantity: 1,
      reason: "Tonalidade não serviu",
      status: "TROCA_SOLICITADA",
      requestedAt: "16/08/2026",
      history: [
        {
          status: "TROCA_SOLICITADA",
          at: "2026-08-16T10:00:00.000Z",
          actor: "CLIENTE",
        },
      ],
    },
    {
      id: "troca-2",
      orderId: "#AUR-25005",
      customerId: "cli-1",
      productId: 8,
      quantity: 1,
      reason: "Produto diferente do esperado",
      status: "TROCA_ACEITA",
      requestedAt: "15/08/2026",
      history: [
        {
          status: "TROCA_SOLICITADA",
          at: "2026-08-15T10:00:00.000Z",
          actor: "CLIENTE",
        },
        {
          status: "TROCA_ACEITA",
          at: "2026-08-16T10:00:00.000Z",
          actor: "ADMIN",
        },
      ],
    },
    {
      id: "troca-3",
      orderId: "#AUR-25005",
      customerId: "cli-1",
      productId: 3,
      quantity: 1,
      reason: "Desejo trocar a cor",
      status: "ITEM_ENVIADO",
      requestedAt: "14/08/2026",
      carrier: "Correios",
      tracking: "BR123456789",
      history: [
        {
          status: "TROCA_ACEITA",
          at: "2026-08-15T10:00:00.000Z",
          actor: "ADMIN",
        },
        {
          status: "ITEM_ENVIADO",
          at: "2026-08-16T10:00:00.000Z",
          actor: "CLIENTE",
        },
      ],
    },
    {
      id: "troca-4",
      orderId: "#AUR-25005",
      customerId: "cli-1",
      productId: 8,
      quantity: 1,
      reason: "Não gostei",
      status: "ITEM_RECEBIDO",
      requestedAt: "12/08/2026",
      carrier: "Correios",
      tracking: "BR987654321",
      restock: true,
      history: [
        {
          status: "ITEM_ENVIADO",
          at: "2026-08-14T10:00:00.000Z",
          actor: "CLIENTE",
        },
        {
          status: "ITEM_RECEBIDO",
          at: "2026-08-16T10:00:00.000Z",
          actor: "ADMIN",
        },
      ],
    },
    {
      id: "troca-5",
      orderId: "#AUR-25005",
      customerId: "cli-1",
      productId: 3,
      quantity: 1,
      reason: "Troca concluída",
      status: "TROCA_PROCESSADA",
      requestedAt: "01/08/2026",
      generatedCouponId: "trade-1",
      history: [
        {
          status: "TROCA_PROCESSADA",
          at: "2026-08-05T10:00:00.000Z",
          actor: "ADMIN",
        },
      ],
    },
    {
      id: "troca-6",
      orderId: "#AUR-25005",
      customerId: "cli-1",
      productId: 8,
      quantity: 1,
      reason: "Fora do prazo",
      status: "TROCA_NEGADA",
      requestedAt: "01/08/2026",
      justification: "Solicitação fora do prazo demonstrativo.",
      history: [
        {
          status: "TROCA_NEGADA",
          at: "2026-08-02T10:00:00.000Z",
          actor: "ADMIN",
        },
      ],
    },
  ],
  audit: [],
};

// Série mensal simplificada para alimentar o dashboard sem depender de backend.
const MESES_ANALYTICS = [
  ["2024-09-01", "Set/24", 0], ["2024-10-01", "Out/24", 7400],
  ["2024-11-01", "Nov/24", 8100], ["2024-12-01", "Dez/24", 10200],
  ["2025-01-01", "Jan/25", 9200], ["2025-02-01", "Fev/25", 11500],
  ["2025-03-01", "Mar/25", 0], ["2025-04-01", "Abr/25", 12600],
  ["2025-05-01", "Mai/25", 13800], ["2025-06-01", "Jun/25", 14900],
  ["2025-07-01", "Jul/25", 14100], ["2025-08-01", "Ago/25", 15600],
  ["2025-09-01", "Set/25", 0], ["2025-10-01", "Out/25", 16300],
  ["2025-11-01", "Nov/25", 17700], ["2025-12-01", "Dez/25", 18400],
  ["2026-01-01", "Jan/26", 16100], ["2026-02-01", "Fev/26", 17300],
  ["2026-03-01", "Mar/26", 12800], ["2026-04-01", "Abr/26", 15400],
  ["2026-05-01", "Mai/26", 0], ["2026-06-01", "Jun/26", 19800],
  ["2026-07-01", "Jul/26", 22200], ["2026-08-01", "Ago/26", 24600],
];

export const CATEGORIAS_ANALYTICS = [
  "Blush", "Paletas", "Lábios", "Olhos", "Bruma", "Limpeza Facial", "Hidratantes",
];

// Distribui o total mensal entre categorias de forma previsível para montar linhas do gráfico.
const PESOS_CATEGORIAS_ANALYTICS = [0.16, 0.14, 0.13, 0.18, 0.1, 0.15, 0.14];

// Histórico agregado usado por partes antigas da aplicação e pelos testes.
export const HISTORICO_ANALYTICS = MESES_ANALYTICS.map(([, label, total]) => [
  label,
  total,
]);

// Histórico detalhado por categoria, usado pelo filtro e pela exportação CSV do dashboard.
export const HISTORICO_ANALYTICS_CATEGORIAS = MESES_ANALYTICS.flatMap(
  ([date, period, total], monthIndex) =>
    CATEGORIAS_ANALYTICS.map((category, categoryIndex) => ({
      date,
      period,
      category,
      value: total
        ? Math.round(
            total *
              PESOS_CATEGORIAS_ANALYTICS[categoryIndex] *
              (1 + ((monthIndex + categoryIndex) % 3 - 1) * 0.035),
          )
        : 0,
    })),
);
